### ISSUE TITLE
Support for HTTP/3 ?

### ISSUE THREAD

**Issue by mrentsch65** [cesanta/mongoose#1243]
Are there any plans to upgrade mongoose to [HTTPv3](https://en.wikipedia.org/wiki/HTTP/3) ?

**Comment by cpq** [comment]
Yeah, that might happen - but when browsers start to request using HTTPv3.
There is a major issue with HTTPv3, namely, Websocket support.
In embedded environment, it is often used for real-time data transfer.
Currently, afaik, there is no standard to support WS via HTTPv3 - and even if there is, making it secure would be a challenge because DTLS is not trivial.
