### ISSUE TITLE
mg_http_get_header returning additional headers

### ISSUE THREAD

**Issue by yourfriendoss** [cesanta/mongoose#1547]
- My goal is: To get a header named X-Token
- My actions were: Using mg_http_get_header
- My expectation was: To only get the X-Token header
- The result I saw: I got the X-Token header, plus more unrelated body content.
- My question is: Why am I getting more stuff other than the X-Token header?

# Environment

- mongoose version: 7.6
- Compiler/IDE and SDK: g++ 10 compiled

## Code
```
        mg_str* token = mg_http_get_header(hm, "X-Token");
        
        
          mg_http_reply(c, 400, "", token->ptr);
          
 ```
## Returns:
   ```
   xtokenTest
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFU2thQjSA6fBuO7o
Accept: */*
Origin: http://0.0.0.0:8080
Referer: http://0.0.0.0:8080/dash.html
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

------WebKitFormBoundaryFU2thQjSA6fBuO7o
Content-Disposition: form-data; name="image"; filename="A.png"
Content-Type: image/png

PNG

```

## Excepted
``` 
xtokenTest
```

**Comment by cpq** [comment]
Thank you @smilediver 

@yourfriendoss - the `struct mg_str` describes a chunk of memory, it is a pointer and length. As @smilediver correctly mentioned, that piece of memory might not be 0-terminated. In case of parsed headers, it is not, because the HTTP request parsing code does not modify the request by inserting zero bytes. The `%s` printf specifier prints until zero. You should use `%.*s` specifier, which lets you tell the length of the string (note also stops at first zero byte):

```
mg_http_reply(c, 400, "", "%.*s", (int)token->len, token->ptr);
```

That also works with `printf()` function. For example, `printf("%.*s\n", 3, "abcdef");`  prints only first 3 characters.

**Comment by yourfriendoss** [comment]
Thanks!
