### ISSUE TITLE
Discrepancy Between Mongoose Versions on Espressif Component Registry and Official Release

### ISSUE THREAD

**Issue by hayschan** [cesanta/mongoose#2595]
### My goal is:
To ensure that the Mongoose version listed on the Espressif Component Registry is up-to-date and consistent with the latest official release on GitHub to prevent confusion and ensure users have access to the latest features and fixes.

### My actions were:
1. I visited the Espressif Component Registry at [this link](https://components.espressif.com/components/cesanta/mongoose).
2. I observed the listed version of Mongoose, which is v7.8.2.
3. I compared it with the latest release on the official Mongoose GitHub page, which is [v7.12](https://github.com/cesanta/mongoose/releases/tag/7.12).

### My expectation was:
The Espressif Component Registry would display the latest version of Mongoose, 7.12, to ensure users are accessing the most recent and secure version of the library.

### The result I saw:
The Espressif Component Registry is displaying an outdated version of Mongoose (v7.8.2) instead of the latest version (7.12). This discrepancy could lead to users missing out on important updates, features, and bug fixes.

### My question is:
Could the process of updating the Mongoose version on the Espressif Component Registry be streamlined or automated to prevent future discrepancies? Would it be possible to integrate the [GitHub action provided by Espressif](https://github.com/espressif/upload-components-ci-action) for automating this update process?

# Environment

- mongoose version: 7.8.2 (listed on the registry) vs 7.12 (latest on GitHub)
- Compiler/IDE and SDK: Not applicable (Issue related to component registry listing)
- Target hardware/board: Not applicable (Issue related to component registry listing)
- Connectivity chip/module: Not applicable (Issue related to component registry listing)
- Target RTOS/OS (if applicable): Not applicable (Issue related to component registry listing)

![Current version of Mongoose on Espressif Component Registry](https://github.com/cesanta/mongoose/assets/25737801/ba9f3442-35b2-4248-b157-f480beb05998)

I believe addressing this issue is crucial for maintaining the integrity and reliability of the Espressif Component Registry. Thank you for your attention and support in resolving this matter.

Best regards,
Hays Chan

**Comment by scaprile** [comment]
We develop and maintain "Mongoose", where "Mongoose" means whatever you can find _here_ in this repo. AFAIK, whatever Espressif does, we can't help. AFAIK, there has never been a Mongoose version with more than "one dot", so that is not our version numbering.
There is no confusion for us nor our user base. Perhaps the maintainers of that registry or Espressif might help you,

You can see how to use Mongoose with the ESP32 if you follow the guidelines in the [documentation](https://mongoose.ws/documentation/),  [examples](https://github.com/cesanta/mongoose/tree/master/examples/) and [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples) available.

https://github.com/cesanta/mongoose/blob/8a9630485f2993da8f10939b32ceb1a601b66e6c/examples/esp32/device-dashboard/Makefile#L3-L4

as you can see:
- we build against their latest IDF available
- we don't use that registry nor anything other than Mongoose itself and the IDF
