### ISSUE TITLE
Coverity - truncated cast.

### ISSUE THREAD

**Issue by jtrack3d** [cesanta/mongoose#2672]
```
    mg_printf(d->c,
              "  <tr><td><a href=\"%.*s%s\">%s%s</a></td>"
              "<td name=%lu>%s</td><td name=%lld>%s</td></tr>\n",
              n, path, slash, name, slash, (unsigned long) t, mod,
              flags & MG_FS_DIR ? (int64_t) -1 : (int64_t) size, sz);
```
2892

A time_t value is stored in an integer with two few bits to accommodate it.  The expression t is cast to unsigned long.

**Comment by scaprile** [comment]
Hello, 
do you have an actual problem ?
The type of time_t is not guaranteed in the C specification.  Unix and POSIX-compliant systems implement the time_t type as a signed integer (typically 32 or 64 bits wide) representing the number of seconds since the Unix epoch.
So, depending on the system where it is compiled, an unsigned long will have more or less bits than time_t.
For the case that it has less, we will need more than 4 teraseconds to meet the time when timestamps reach a sign overflow in a 64-bit signed integer. Our timers use 64-bit for that reason, to simplify code calculations, and here what might happen, 136 years from now, is that, if enabled, directory entries will print bogus timestamps.

Please honor the issue template
