### ISSUE TITLE
Coverity - Out-of-bounds-access

### ISSUE THREAD

**Issue by jtrack3d** [cesanta/mongoose#2673]
```
    case MQTT_PROP_TYPE_VARIABLE_INT:
      len = decode_varint(i, (size_t) (end - i), (size_t *) &prop->iv);
      new_pos = (!len) ? 0 : new_pos + len;
      break;

```
4301 - Mongoose.c

Coverity - Pointer &prop->iv points to an object whose effective type is unsigned int (32) but is dereferences as a wider unsigned long long (64-bit unsigned).  This may lead to memory corruption.

**Comment by scaprile** [comment]
Hello,
decode_varint() takes care of failing when it can't provide proper results. IIRC that has been audited and passed a year ago.
Do you think otherwise ? Do you have an actual problem ? Can you elaborate ? Then please honor the issue template, and tell us your thoughts, you can always reopen this issue if necessary.
