### ISSUE TITLE
Support for passing listening sockets to Mongoose

### ISSUE THREAD

**Issue by MattK2K4** [cesanta/mongoose#2913]
My goal is to bring systemd socket based activation to an project using mongoose. For that its necessary for the webserver/mongoose to listen on an existing socket. I saw that is functionality was available in [previous versions ](https://github.com/cesanta/mongoose/pull/107)of mongoose. In the current version all connect functions seem to require a URL as an argument and therefore create the socket themselves.

My question is: Is there still a way to start mongoose with an existing socket (e.g. by passing the filedescriptor)?

**Comment by scaprile** [comment]
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
You'll see there is no function for that.
Your link is from 2013. Mongoose has strongly oriented towards embedded since them.
Perhaps you'd want to join #2812 or propose how to do that on a feature request. Since this is not a Mongoose issue, I'm closing this.
