### ISSUE TITLE
Error: expected Finish but got msg 0x02 (Fixed)

### ISSUE THREAD

**Issue by x893** [cesanta/mongoose#2960]
Hi,
time too time i see error in mg_tls_server_recv_finish(...)
After investigate i found that chrome send MG_TLS_SERVER_HELLO instead MG_TLS_FINISHED.
To solve the problem I add the following codes:
```
	recv_buf = &c->rtls.buf[tls->recv_offset];
	if (recv_buf[0] == MG_TLS_SERVER_HELLO) {
		// Server send MG_TLS_SERVER_HELLO without MG_TLS_FINISHED
	}
	else if (recv_buf[0] != MG_TLS_FINISHED) {
		mg_error(c, "expected Finish but got msg 0x%02x", recv_buf[0]);
		return -1;
	}
	else {
		mg_tls_drop_message(c);
	}
```
Thanks for mongoose !
P.S. It's real awesome

**Comment by scaprile** [comment]
The issue template is there for a reason: to save yours and our time. Please honor the issue template and fill it as requested.
We already know and test code, it is _your_ code we need to see to know if you are using Mongoose properly. Please provide the bare minimum piece of code that reproduces your issue.
Please see our [documentation](https://mongoose.ws/documentation/),  and follow the guidelines in our [tutorials](https://mongoose.ws/documentation/#tutorials-and-examples).
Please sniff your network (using Wireshark, for example) and observe the traffic.
If, after your network inspection, you find an actual issue, feel free to open an issue, fill the issue template, and provide us with pertinent information (including useful network capture files; no snapshots, please attach capture files) in order to reproduce and fix the issue. We don't inspect your code for errors, please send the minimum piece of code that can reproduce the issue
