### ISSUE TITLE
cgi requests in Mongoose on an embedded riscv not working

### ISSUE THREAD

**Issue by smartelements** [cesanta/mongoose#2983]
### Discussed in https://github.com/cesanta/mongoose/discussions/2403

I managed to get the websocket server running on my MilkV-DUO without any problems, but when I tried to use cgi scripts in mongoose but after several hours I still get plain text output instead of execution of the scripts. How can I get ti to work ? I read ALL docs and checked ALL examples, just not to get the answer: "Read the docs".

I set the correct flags on compiling and set the appropriate patterns but I still get plain text out of my simplest cgi scripts.
On all other server solutions this was a question of a few minutes to get it work. It would be a pity if for that reason I cannot use Mongoose. It should not be that complicated!? Thank you for your help!

I compile with  riscv64-linux-musl-gcc -o -static

**Comment by scaprile** [comment]
Well, should I say "understand the docs, understand the examples" ?
Mongoose is C code, you get a C function called on every request, have you seen the UI ? have you seen the JSON examples ? all that is equivalent to whatever you want to do with a CGI.
Mongoose that what the docs say, it does not do what the docs don't say. Mongoose does not execute anything, unless you told it to do by calling a system function in your handler, because Mongoose is C code and you can do whatever you want to do in C code, thing that is made perfectly clear in at least the very first link in the discussion you posted before, where a static server and a dynamic server with an API where shown, and in the last link in the same place, where a whole dynamic UI is discussed.

There are no "correct flags in compiling", you have to write C code, all the examples and tutorials show you how to write C code in event handlers, all the docs describe C-callable functions and event handlers. Mongoose is not "a server", Mongoose is a Network Library. Mongoose is not a program for Linux nor Windows, Mongoose can run in bare metal in 8-bit micros where there is no operating system nor the notion of a script. Please understand what the server tutorial explains, and if you don't, then first understand the concepts behind.
