### ISSUE TITLE
Using Teensy ADC Library with Mongoose causes Out of Memory errors

### ISSUE THREAD

**Issue by chriskinal** [cesanta/mongoose#2984]
- My goal is to use Mongoose WS to create a GUI for a Teensy project that uses the Teensy ADC library.
- My actions were I created a default Mongoose Wizard project. Created an ADC instance with the teensy Arduino ADC class.
- Here is the 3 lines of code that cause the issue. 
`#include <ADC.h>
  #include <ADC_util.h>
  ADC* teensyADC = new ADC();`
- My expectation was the Mongoose ethernet driver would initialize.
- The result I saw Out of Memory errors when the ethernet driver tried to initialize.
244    2 mongoose.c:17712:mg_phy_init   PHY ID: 0x2000 0xa140 (DP83825)
252    1 mongoose.c:5113:mg_tcpip_init  OOM
252    2 mongoose.c:4053:mg_mgr_init    Driver: imxrt, MAC: 02:ee:7e:3a:26:d7
252    2 mongoose_impl.c:680:mongoose_i Starting HTTP listener
252    1 mongoose.c:3966:mg_listen      OOM http://0.0.0.0:80
252    2 mongoose_impl.c:716:mongoose_i Mongoose init complete, calling user init
252    3 mongoose_glue.c:11:glue_init   Custom init done
252    1 mongoose.c:4996:mg_tcpip_poll  Network is down
62c    1 mongoose.c:4996:mg_tcpip_poll  Network is down
a14    3 mongoose.c:17615:mg_tcpip_driv Link is 100M full-duplex
a14    1 mongoose.c:4276:onstatechange  Link up

- My question is how to get Mongoose WS and Teensy ADC to work together.

# Environment

- mongoose version: 7.19
- Compiler/IDE and SDK: VSCode 1.95.3 / PlatformIO / Arduinoteensy 1.59
- Target hardware/board: Teensy 4.1
- Connectivity chip/module: On board.
- Target RTOS/OS (if applicable): Arduino

**Comment by scaprile** [comment]
- Mongoose 7.19 does not exist (yet)
- Mongoose does not know, nor care, what an ADC is. If your system is running out of memory because some library or your code uses memory, there's nothing we can do. There is no "work together", you either have enough memory or you don't; unless, of course, one of the libraries is broken, in which case you fix it, and ours, AFAIK, is not.
- If you know how to read a datasheet, check how much memory you have, 
- If you know how to read a map file, check where your memory is going
  - Mongoose will take around 6KB static for DMA descriptors and ETH buffers
    - https://github.com/cesanta/mongoose/blob/d44c86438796a5e6be9606a389c21ef7119719e6/src/drivers/imxrt.c#L34 https://github.com/cesanta/mongoose/blob/d44c86438796a5e6be9606a389c21ef7119719e6/src/drivers/imxrt.c#L45-L53
  - and then alloc 1.5KB for tx buffer and 8KB for its receive queue, that is what is failing, your heap is not big enough.
    - https://github.com/cesanta/mongoose/blob/d44c86438796a5e6be9606a389c21ef7119719e6/src/net_builtin.c#L1034-L1038
    - You can try trimming the receive queue size by manually setting `recv_queue.size` in mongoose_config.h, but you should first know why
- Check your system configuration for heap size
- If you know how to use a debugger, check who is allocating your memory
