### ISSUE TITLE
mg_destroy_server crashes when server uses HTTPS/SSL and multiple threads

### ISSUE THREAD

**Issue by ludekvodicka** [cesanta/mongoose#441]
Hi,

I'm trying to configure mongoose to be able to handle multiple client requests at once. I have found following example: https://github.com/cesanta/mongoose/blob/master/examples/multi_threaded_server/multi_threaded_server.c

But when I initialize servers with ssl certificate:

     	mg_set_option(server1, "listening_port", "ssl://443:stark.pem");

instead of original

      mg_set_option(server1, "listening_port", "8080");

and call mg_destroy_server on exit, application crashes when destroying second SSL server instance.

This is crash callstack:

![Crash callstack](http://i.imgur.com/X4KmZym.png)

and crash location
![Crash location](http://i.imgur.com/AcKWMDk.png)

it seems that SSL certificate is destroyed multiple times in case the connection is sharing them via mg_copy_listeners. 

Is this a bug or am I doing something wrong in the initialization? Is this a valid way how to create mongoose server instance able to handle multiple requests?

Complete test case to simulate this behavior:

    static int ev_handler(struct mg_connection *conn, enum mg_event ev) 
    {
    	if ( ev == MG_REQUEST )
    	{
    		mg_send_header(conn, "Content-Type", "text/plain");
    		mg_printf_data(conn, "This is a reply from server instance # %s",
    									 (char *)conn->server_param);
    		return MG_TRUE;
    	}
    	else if ( ev == MG_AUTH )
    		return MG_TRUE;
    	else
    		return MG_FALSE;
    }
    
    static bool bStop = false;
    static void *serve(void *server) {
    	struct mg_server * srv = (struct mg_server *)server;
    	while ( bStop == false ) mg_poll_server(srv, 1000);
    	mg_destroy_server(&srv); // <<<<< CRASHED here when destroying second instance
    	return NULL;
    }
    
    AX_EXPLICIT_TEST_CASE(mongoose_run_server_https_test)
    {
    	struct mg_server *server1, *server2;
    
    	server1 = mg_create_server((void *) "1", ev_handler);
    	server2 = mg_create_server((void *) "2", ev_handler);
    
    	// Make both server1 and server2 listen on the same sockets
    	mg_set_option(server1, "listening_port", "ssl://8080:server.pem");
    	mg_copy_listeners(server1, server2);
    
    	// server1 goes to separate thread, server 2 runs in main thread.
    	// IMPORTANT: NEVER LET DIFFERENT THREADS HANDLE THE SAME SERVER.
    	mg_start_thread(serve, server1);
    	mg_start_thread(serve, server2);
    
    	Delay(1000 * 10);
    	bStop = true;
    }

**Comment by ahmed00medhat** [comment]
i can't compile mongoose because of this fix, any suggestions please?

> <pre>[ 83%] <font color="#4E9A06"><b>Linking CXX executable app</b></font>

> [ 83%] Built target app
> [ 83%] <font color="#4E9A06">Building C object cpr/opt/CMakeFiles/mongoose.dir/mongoose/mongoose.c.o</font>
> <b>/home/ahmed/applications/C++/C-Web-Client/cpr/opt/mongoose/mongoose.c:</b> In function ‘<b>mg_copy_listeners</b>’:
> <b>/home/ahmed/applications/C++/C-Web-Client/cpr/opt/mongoose/mongoose.c:5110:21:</b> <font color="#CC0000"><b>error: </b></font>dereferencing pointer to incomplete type ‘<b>SSL_CTX</b>’ {aka ‘<b>struct ssl_ctx_st</b>’}
>  5110 |         tmp-&gt;ssl_ctx<font color="#CC0000"><b>-&gt;</b></font>references++;
>       |                     <font color="#CC0000"><b>^~</b></font>
> make[2]: *** [cpr/opt/CMakeFiles/mongoose.dir/build.make:63: cpr/opt/CMakeFiles/mongoose.dir/mongoose/mongoose.c.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:357: cpr/opt/CMakeFiles/mongoose.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> </pre>
> 

the openssl library installed details are as below:

>Package: libssl-dev
Version: 1.1.1f-1ubuntu2
Priority: optional
Section: libdevel
Source: openssl
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 8,005 kB
Depends: libssl1.1 (= 1.1.1f-1ubuntu2)
Suggests: libssl-doc
Conflicts: libssl1.0-dev
Homepage: https://www.openssl.org/
Download-Size: 1,582 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
Description: Secure Sockets Layer toolkit - development files
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains development libraries, header files, and manpages for libssl
 and libcrypto.

**Comment by balramneato** [comment]
Any update on this issue.
