### ISSUE TITLE
mg_broadcast and message data - by reference or by value

### ISSUE THREAD

**Issue by nkolban** [cesanta/mongoose#742]
I am studying mg_broadcast() API found here ...

https://docs.cesanta.com/mongoose/master/#/c-api/net.h/mg_broadcast.md/

My question is in relation to the data supplied by a caller to mg_broadcast().  Is the data payload passed into mg_broadcast() copied or passed by reference to the specified event handler?

My back story is that if I am working with malloc() storage, I went to know when and by whom to free() it up and knowing whether it is copied or passed by reference is essential to handling this.  I am also assuming that if passed by copy then the event handler need not release the buffer passed in on the event.

Might I suggest that this answer could be used to update the excellent existing docs for clarity?

**Comment by cpq** [comment]
Hi Neil!

`mg_broadcast()` is copied. Basically, since the control socket pair is UDP, it does not block, therefore Mongoose just sends the data directly into the socket:

https://github.com/cesanta/mongoose/blob/3a611864912da4e4d18d5fed2e0b0a60fb4352d3/mongoose.c#L2843-L2846

The message gets further copied into the socket buffer of the network stack (LWIP in this case). Mongoose code does not use malloc/free in this code path. LWIP might.
