### ISSUE TITLE
fd < FD_SETSIZE needs checking before FD_SET is called

### ISSUE THREAD

**Issue by henryr** [cesanta/mongoose#90]
Just finished debugging a very painful issue where a fd > 1024 was causing a buffer overflow. 

The right thing to do is to use poll, and I see that's the default now, but in cases where only select is available the fd should be checked.

**Comment by Tigzy** [comment]
Hello, I just found a similar issue where FD_SETSIZE is checked in ns_add_to_set, and when the socket created is highler to that value (surprisingly that happens to me only in release mode) then ns_mgr_poll will always return 0 because of empty read_set/write_set. Plus, not sure why but this bug also leads to high CPU usage (25% with bug, 1% without bug)

**Comment by Tigzy** [comment]
Maybe a clue: 
mongoose.c, line 836: 
// NOTE(lsm): on Windows, sock is always > FD_SETSIZE
mongoose.c, line 1068:
if ( (sock != INVALID_SOCKET) && (sock < FD_SETSIZE) ) {
(note, this is the check I'm talking about earlier, in ns_add_to_set)

**Comment by Tigzy** [comment]
After changing changing #define FD_SETSIZE definition to 2048, no more bug. 
But I don't think this is the correct way to do, ugly workaround.
