### ISSUE TITLE
Some Heap Buffer Overflow Detected

### ISSUE THREAD

**Issue by TiffanyBlue** [cesanta/mongoose#984]
Hello, I have detected some vulnerabilities about MQTT on latest version 6.13. The links followed will show you the details and PoC.
https://github.com/TiffanyBlue/PoCbyMyself/tree/master/mongoose6.13/mqtt

**Comment by cpq** [comment]
Absolutely, we're looking at it. Thank you for the report.

**Comment by dreadlocked** [comment]
I checked this vulnerability, it seems not to be exploitable, also only two bytes can be readed. The mqtt_parse function checks if p > end, if so, program dies after any information is returned.

The problem is, user can control the variable header lenght, if you supply a lenght that is end+1 length, the second call to scanto() on any MQTT message type (for example MQTT_CONNECT), will try to access up[1] on getu16() call, but up[1] will be out of bounds. If you use ASAN when compiling, the application crash, if not, the application will continue, but then, it will check if p > end. This condition will met, as p pointer is increased during scanto() and the program will just exit.

I can't ensure that others could exploit this issue or chain this issue with other vulnerabilities. Also, on architectures other than 32/64 bits, this issue could be dangerous.

**Comment by cpq** [comment]
@dreadlocked thanks for the background, appreciated!

**Comment by cpq** [comment]
Closing this, as it is apparently fixed in the latest code.
Thank you!
